# Implimentation of GradientDescent on Multiple_Dimension on BostonDatasets

In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets #imported Boston datasets as it have multidimensional input featured

In [2]:
boston=datasets.load_boston()
print(type(boston))

<class 'sklearn.utils._bunch.Bunch'>


C:\Users\KIIT\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np

        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.

In [3]:
boston.DESCR

".. _boston_dataset:\n\nBoston house prices dataset\n---------------------------\n\n**Data Set Characteristics:**  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate per $10,000

In [34]:
X=boston.data
Y=boston.target
print(type(X))
print(type(Y))
print(X.shape,Y.shape)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
(506, 13) (506,)


In [35]:
df=pd.DataFrame(X)#It would create 2Dtable: (Rows,Coloumn),in which X was form of numpyArray and as you know from oandas if there is no coloumn headings the by-deafult first-row becomes that 
print(boston.feature_names)#Now this would be pur coloumnHeader,repreents different types of input(features of input)
df.columns=boston.feature_names#Now those feeaureNames are columnHeaders
print(df.describe())#Describes dataRepresentation Heavily
print(df)

['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']
             CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    

In [36]:
df.isnull().sum()
df.index

RangeIndex(start=0, stop=506, step=1)

In [37]:
from sklearn import model_selection

X_train,X_test,Y_train,Y_test=model_selection.train_test_split(X,Y)

#Sizes
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(379, 13)
(379,)
(127, 13)
(127,)


In [38]:
print(len(X_train))
print(X_train[0][:].shape)
print(X_train)

379
(13,)
[[1.0008e-01 0.0000e+00 2.4600e+00 ... 1.7800e+01 3.9690e+02 5.6800e+00]
 [5.4970e-02 0.0000e+00 5.1900e+00 ... 2.0200e+01 3.9690e+02 9.7400e+00]
 [1.0574e-01 0.0000e+00 2.7740e+01 ... 2.0100e+01 3.9011e+02 1.8070e+01]
 ...
 [1.9802e-01 0.0000e+00 1.0590e+01 ... 1.8600e+01 3.9363e+02 9.4700e+00]
 [6.4660e-02 7.0000e+01 2.2400e+00 ... 1.4800e+01 3.6824e+02 4.9700e+00]
 [1.5445e-01 2.5000e+01 5.1300e+00 ... 1.9700e+01 3.9068e+02 6.8600e+00]]


# GradientDescent-Parameters:
### 1)Data-TrainingData & TestingData
### 2)Learning_Rate(alpha)
### 3)Number_Of_Iterations
### 4)INstead of m and c ,Passed m-array for m in each row including c at last

In [39]:
# Here in multi-variable , we would pass the all m in array-formate including c inside it at last  

#Defining function which would calculate new m and c for a single step
def step_gradient(X_train,Y_train,learning_rate,m,c):
    # m=np.array([0 for i in range(13)])
    m_slope=[0 for i in range(13)]
    c_slope=0
    M=len(X_train)
    # x=np.array([1 for i in range(13)])
    # print(x.shape, m.shape,X_train[0][:].shape)

    for i in range(M):
        y=Y_train[i]
        # it will copy all 13 element from X_train and also put 1 at the end that is at 14th element
        # x=np.appened(X_train[i][:],1)
        x = X_train[i][:] 
        # print(x.shape)
        for j in range(13):
            m_slope[j]+=(-2/M)*(y-np.dot(m,x)-c)*x[j]
        c_slope+=(-2/M)*(y-np.dot(m,x)-c)

    new_m=[m[i]-learning_rate*m_slope[i] for i in range(13)]
    new_c=c-learning_rate*c_slope
    return (new_m,new_c)

In [40]:
#Defining GradientDescent-function as gd
def gd(X_train,Y_train,learning_rate,num_iterations):      
    #At first we should have random values of m and c
    m=[0 for i in range(13)]
    c=0
    for i in range(num_iterations):#We should update these m,c values for number iteration times
        m,c=step_gradient(X_train,Y_train,learning_rate,m,c) #Another function made which would calculate sinleStep-GradientDescent
        current_cost = cost(X_train, Y_train, m, c)  # Calculate cost for current parameters
        print(f"Iteration {i+1}, Cost: {current_cost}")
    return (m,c)

In [41]:
#Defining costFunction which could return the instantenousCost function
def cost(X_train,Y_train,m,c):
    total_cost=0
    cost=0
    M=len(X_train)
    for i in range(M):
        y=Y_train[i]
        x=X_train[i][:]
        cost+=((y-m*x-c)**2)
    total_cost=1/M*(np.sum(cost))
    return total_cost

In [42]:
#Defined a function where the resepctive parameters are passed and called GradoentFunction as "gd" 
def run():
    learning_rate=0.00001
    num_iterations=100
    m,c=gd(X_train,Y_train,learning_rate,num_iterations)
    print(m,c)
    return m,c


In [43]:
m,c=run()

Iteration 1, Cost: 11107.3719325161
Iteration 2, Cost: 205083.59206123117
Iteration 3, Cost: 5059310.3485364355
Iteration 4, Cost: 142738598.32183084
Iteration 5, Cost: 3950564431.6569023
Iteration 6, Cost: 109773255092.84193
Iteration 7, Cost: 3047961828294.636
Iteration 8, Cost: 84641712668279.39
Iteration 9, Cost: 2350431455331855.0
Iteration 10, Cost: 6.526990411437506e+16
Iteration 11, Cost: 1.8124996622409907e+18
Iteration 12, Cost: 5.033185937214918e+19
Iteration 13, Cost: 1.3976808004084263e+21
Iteration 14, Cost: 3.8812625983852075e+22
Iteration 15, Cost: 1.0777996903242514e+24
Iteration 16, Cost: 2.99297494899174e+25
Iteration 17, Cost: 8.311283743446015e+26
Iteration 18, Cost: 2.3079858215298094e+28
Iteration 19, Cost: 6.409116469612058e+29
Iteration 20, Cost: 1.7797671691864284e+31
Iteration 21, Cost: 4.942289926438846e+32
Iteration 22, Cost: 1.3724396168148709e+34
Iteration 23, Cost: 3.8111695789570304e+35
Iteration 24, Cost: 1.0583353454395915e+37
Iteration 25, Cost: 2.93