# Implimentation of Decision Tree

## Importing all libraries

In [78]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets # for importing the datasets
from sklearn.tree import DecisionTreeClassifier # for getting decisionTree classifier from sklearn.tree library
from sklearn.model_selection import train_test_split

# For exporting the existing decisionTree into the pdf for visualInspection of the tree not come with conda should have to install this
from sklearn.tree import export_graphviz 
import pydotplus


## Loading the dataset from sklearn 's datasets library

In [68]:
iris= datasets.load_iris()
type(iris) # in 2d array dimnesion, bunch(class in scikitLearn) is type of representation of the data for easy sending 

sklearn.utils._bunch.Bunch

## Converting the Bunch typeDatasets into Dataframe type for easy examining

In [97]:
# Convert Bunch to DataFrame 
iris_df = pd.DataFrame(data=iris.data,columns= iris.feature_names)
iris_df['target'] = iris.target

# Display the DataFrame  
print(iris_df) # For displaying intial datapoints
iris_df.target=iris.target

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  

In [85]:
iris_df


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [101]:
type(iris.data)

numpy.ndarray

## Spliting the training and testing datas

In [100]:
# Now splitting the datasets
X_train,X_test,Y_train,Y_test=train_test_split(iris.data,iris.target,test_size=0.3,random_state=1)

## Intilising the object of the classifierClass and training thr model

In [72]:
# Using the decisionTree classifier, imported earlier
clf=DecisionTreeClassifier()
clf.fit(X_train,Y_train)

DecisionTreeClassifier()

## Passing the classifier tree to the function for getting its visulaisation

In [93]:
# Passed the classifier into the object 
# "out_file=None" means we donont want to save the file outside, in ".dot" formate instead this function would return the data and other parameters given
# -for coloring, shaping and displaying the feature name and classes
# and in next function used to vizsualise and render the grpah into png formate

# Visualize the decision tree
dot_data = export_graphviz(clf, out_file=None, feature_names=iris.feature_names, class_names=iris.target_names,
                           filled=True, rounded=True, special_characters=True)

graph = graphviz.Source(dot_data)
graph.render("iris_decision_tree1", format='png', cleanup=True)

# dot_data = StringIO()
# export_graphviz(clf, out_file=dot_data, filled=True, rounded=True, special_characters=True)
# graph = pydotplus.graph_from_dot_data(dot_data.getvalue()) 
# Image(graph.create_png())


## Model Predictions

In [79]:
# Having model predictions
Y_test_pred=clf.predict(X_test)
Y_train_pred=clf.predict(X_train)

## Now checking the model working from metrics on traiining data

In [80]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(Y_train,Y_train_pred))
print()
print(accuracy_score(Y_train,Y_train_pred))

[[36  0  0]
 [ 0 32  0]
 [ 0  0 37]]

1.0


In [81]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(Y_test,Y_test_pred))
print()
print(accuracy_score(Y_test,Y_test_pred))

[[14  0  0]
 [ 0 17  1]
 [ 0  1 12]]

0.9555555555555556


In [82]:
from sklearn.metrics import classification_report
print(classification_report(Y_train,Y_train_pred))


              precision    recall  f1-score   support

           0       1.00      1.00      1.00        36
           1       1.00      1.00      1.00        32
           2       1.00      1.00      1.00        37

    accuracy                           1.00       105
   macro avg       1.00      1.00      1.00       105
weighted avg       1.00      1.00      1.00       105



## Now check the model working from metrics on testing

In [83]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(Y_test,Y_test_pred))
print()
print(accuracy_score(Y_test,Y_test_pred))      


[[14  0  0]
 [ 0 17  1]
 [ 0  1 12]]

0.9555555555555556


In [84]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,Y_test_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.94      0.94      0.94        18
           2       0.92      0.92      0.92        13

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45

